<?php
/**
 * @var \Firework\Firework\Block\System\Config\ConnectButton $block
 */
?>
<script>
    require([
        'jquery',
        'mage/validation',
        'prototype',
    ], function ($, mage) {
        var dataForm = $('#config-edit-form');
        dataForm.mage('validation', {});
        function connectButton() {
            
            var enable = $('#firework_general_enable').val();
            var oauthUserToken = $('#firework_general_integration_token').val();
            var oauthUserClient = $('#firework_general_oauth_user_client').val();
            var oauthUserSecret = $('#firework_general_oauth_user_secret').val();
            
            <?php $storeData = $block->getCurrentStoreAndWebsite() ?>
            
            var formData = {
                'enable':enable,
                'store_id' : "<?= /* @noEscape */ $storeData['store_id'] ?>",
                'store_scope' : "<?= /* @noEscape */ $storeData['scope'] ?>",
                'integration_token': oauthUserToken,
                'oauth_user_client': oauthUserClient,
                'oauth_user_secret': oauthUserSecret
            };

            new Ajax.Request('<?= /* @noEscape */ $block->getAjaxUrl() ?>', {
                loaderArea: true,
                asynchronous: true,
                parameters: formData,
                onSuccess: function (transport) {
                var response = JSON.parse(transport.responseText);
                console.log(response);
                if(response.message === 'successUrl') {
                    window.location.href = response.redirectUrl;
                    return false;
                }
                if (response.message === 'false') {
                    location.reload();
                    return false;
                }
                if (response.message === 'error') {
                    $('#messages .message-error span.message-text').text('Something went wrong. Please try agian.');
                    $('#messages .message-error').show();
                    $('#messages .message-error').delay(8000).fadeOut();
                    return false;
                } else {
                    window.open(response.second_api_url);
                }
                },
                onFailure: function() {
                    $('#messages .message-error span.message-text').text('Something went wrong. Please try agian.');
                    $('#messages .message-error').show();
                    $('#messages .message-error').delay(8000).fadeOut();             
                    return false;
                }
            });
        }
        $('#connectbutton').click(function () {
            var status = dataForm.validation('isValid');
            if (status) {
                connectButton();
            }
        });
    });
</script>

<div id="messages" >
    <div class="messages">
        <div class="message message-success success" style="display: none;">
            <div data-ui-id="messages-message-success">
                <span class="message-text"></span>
            </div>
        </div>
        <div class="message message-error error" style="display: none;">
            <div data-ui-id="messages-message-error">
                <span class="message-text"></span>
            </div>
        </div>
    </div>
</div>
<?= /* @noEscape */ $block->getButtonHtml() ?>
<?= /* @noEscape */ $block->getCurrentStore(); ?>