<?php
/**
 * @var \Firework\Firework\Block\System\Config\ResetBusiness $block
 */
?>
<script>
    require([
        'jquery',
        'mage/validation',
        'prototype',
    ], function ($, mage) {
        var dataForm = $('#config-edit-form');
        dataForm.mage('validation', {});
        function resetBusiness() {

            <?php $storeData = $block->getCurrentStoreAndWebsite() ?>
            
            var formData = {
                'store_id' : "<?= /* @noEscape */ $storeData['store_id'] ?>",
                'store_scope' : "<?= /* @noEscape */ $storeData['scope'] ?>",
            };

            new Ajax.Request('<?= /* @noEscape */ $block->getAjaxUrl() ?>', {
                loaderArea: false,
                asynchronous: true,
                parameters: formData,
                onSuccess: function (transport) {
                var response = JSON.parse(transport.responseText);
                if(response.message === 'successUrl') {
                    location.reload()
                    return false;
                }
                },
                onFailure: function() {
                    $('#messages .message-error span.message-text')
                    .text('Something went wrong. Please contact to store owner.');
                    $('#messages .message-error').show();
                    $('#messages .message-error').delay(8000).fadeOut();             
                    return false;
                }
            });
        }
        $('#resetbusiness').click(function () {
            var status = dataForm.validation('isValid');
            if (status) {
                resetBusiness();
            }
        });
    });
</script>

<div id="messages" >
    <div class="messages">
        <div class="message message-success success" style="display: none;">
            <div data-ui-id="messages-message-success">
                <span class="message-text"></span>
            </div>
        </div>
        <div class="message message-error error" style="display: none;">
            <div data-ui-id="messages-message-error">
                <span class="message-text"></span>
            </div>
        </div>
    </div>
</div>
<?= /* @noEscape */ $block->getButtonHtml() ?>
