<?php
$values = $block->getValues();
$settings = (isset($values['settings']['grid'])) ? $values['settings']['grid'] : [] ;

$videoShow = (isset($settings['video_show'])) ? $settings['video_show'] : '';
$videoShowValue = (isset($videoShow['value'])) ? $videoShow['value'] : '';
$placement = (isset($settings['position'])) ? $settings['position'] : '';
?>

<div class="grid">
            
    <div class="video_show field ">
        <label class="option-title">
            <?= /* @noEscape */ __('Video shown in grid') ?>
        </label>
        <div class="control">
            <ul class="field-options">
                <li>
                    <input
                        type="radio"
                        id="grid-value-infinite"
                        name="parameters[data][settings][grid][video_show][value]"
                        value="infinite" <?= ($videoShowValue == 'infinite') ? "checked" : '' ?>
                    />
                    <label for="grid-value-infinite">
                        <?= /* @noEscape */ __('Infinite') ?>
                    </label>
                </li>
                <li>
                    <input
                        type="radio"
                        id="grid-value-load"
                        name="parameters[data][settings][grid][video_show][value]"
                        value="load" <?= ($videoShowValue == 'load') ? "checked" : '' ?>
                    />
                    <label for="grid-value-load">
                        <?= /* @noEscape */ __('Load') ?>
                    </label>
                </li>
                <li>
                    <div class="admin__field admin_field_right">
                        <div class="admin__field-control">
                            <?php $videoShow = ($videoShowValue == 'load') ? $settings['video_show']['number'] : ''; ?>
                            <input
                                type="text"
                                id="grid-number"
                                name="parameters[data][settings][grid][video_show][number]"
                                class="admin__control-text"
                                value="<?= /* @noEscape */ $videoShow ?>"
                            />
                        </div>
                        <div class="admin__field-label">
                            <label class="label admin__field-label" for="grid-number">
                                <?= /* @noEscape */ __('video at a time') ?>
                            </label>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="placement">
        <div class="field">
            <label class="option-title">
                <?= /* @noEscape */ __("Minimized video player location") ?>
            </label>
            <div class="control">
                <ul class="field-options">        
                    <li>
                        <input
                            type="radio"
                            id="grid-position-bottom_right"
                            name="parameters[data][settings][grid][position]"
                            value="bottom-right" <?= ($placement == 'bottom_right') ? "checked" : '' ?>
                        />
                        <label for="grid-position-bottom_right">
                            <?= /* @noEscape */ __('Bottom Right') ?>
                        </label>
                    </li>
                    <li>
                        <input
                            type="radio"
                            id="grid-position-bottom_left"
                            name="parameters[data][settings][grid][position]"
                            value="bottom-left" <?= ($placement == 'bottom_left') ? "checked" : '' ?>
                        />
                        <label for="grid-position-bottom_left">
                            <?= /* @noEscape */ __('Bottom Left') ?>
                        </label>
                    </li>
                    <li>
                        <input
                            type="radio"
                            id="grid-position-top_right"
                            name="parameters[data][settings][grid][position]"
                            value="top-right" <?= ($placement == 'top_right') ? "checked" : '' ?>
                        />
                        <label for="grid-position-top_right">
                            <?= /* @noEscape */ __('Top Right') ?>
                        </label>
                    </li>
                    <li>
                        <input
                            type="radio"
                            id="grid-position-top_left"
                            name="parameters[data][settings][grid][position]"
                            value="top-left" <?= ($placement == 'top_left') ? "checked" : '' ?>
                        />
                        <label for="grid-position-top_left">
                            <?= /* @noEscape */ __('Top Left') ?>
                        </label>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>